/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

/**
 * Ventana de diálogo en la que se especificará el tamaño de la ventana interna imagen
 * @author Manuel Alonso Braojos
 */
public class TamañoVentana extends javax.swing.JDialog {

    private int ancho;
    private int high;
    
    /**
    * Constructor por defecto de la clase TamañoVentana
    */
    public TamañoVentana() {
        
    }
    
   /**
    * Constructor por parámetros de la clase TamañoVentana
    * 
    * @param parent ventana padre desde donde saltará el diálogo
    * @param modal especifica si la entrada de bloques de diálogo de usuario a otros de nivel superior
    */
    public TamañoVentana(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
    * Método para devolver la altura de la ventana
    * 
    * @return high altura de la ventana
    */
    public int getHigh() {
        return high;
    }

    /**
    * Método para modificar la altura de la ventana
    * 
    * @param high nueva altura de la ventana
    */
    public void setHigh(int high) {
        this.high = high;
    }

    /**
    * Método para devolver el ancho de la ventana
    * 
    * @return ancho el ancho de la ventana
    */
    public int getAncho() {
        return ancho;
    }

    /**
    * Método para modificar el ancho de la ventana
    * 
    * @param ancho nuevo ancho de la ventana
    */
    public void setAncho(int ancho) {
        this.ancho = ancho;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        anchoField = new javax.swing.JTextField();
        altoField = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(null);

        anchoField.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(anchoField);
        anchoField.setBounds(170, 110, 50, 30);

        altoField.setForeground(new java.awt.Color(51, 153, 255));
        jPanel1.add(altoField);
        altoField.setBounds(170, 150, 50, 30);

        botonAceptar.setForeground(new java.awt.Color(255, 51, 51));
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(botonAceptar);
        botonAceptar.setBounds(130, 190, 71, 23);

        jLabel1.setText("Ancho:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(94, 120, 50, 14);

        jLabel2.setText("Alto:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 150, 23, 14);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Capta la información requerida en los campos de texto del diálogo
     * @param evt acción de pulsar el botón Aceptar
     */
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        if(this.altoField!=null){
            this.ancho= Integer.valueOf(this.anchoField.getText());
        }
        
        if(this.altoField!=null){
            this.high= Integer.valueOf(this.altoField.getText());
        }
        this.setVisible(false);
    }//GEN-LAST:event_botonAceptarActionPerformed

    
    
    
    
    
    

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altoField;
    private javax.swing.JTextField anchoField;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
