/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;
import sm.sound.SMRecorder;
import sm.sound.SMSoundRecorder;

/**
 * Crea una ventana interna de grabación de audio
 * @author Manuel Alonso Braojos
 */
public class VentanaInternaGrabador extends javax.swing.JInternalFrame {

    
    private SMSoundRecorder player;
    
    /**
     * Constructor por parámetros de la clase VentanaInternaGrabador
     * @param f archivo de tipo File donse guardará la grabación
     */
    public VentanaInternaGrabador(File f) {
        initComponents();
        player=new SMSoundRecorder(f); 
        //player.setLineListener(new ManejadorAudio());
    }

    /**
     * Método que devuelver el player
     * @return player objeto player
     */
    public SMSoundRecorder getPlayer() {
        return player;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
