/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Robot;
import sm.graficos.Figura;
import sm.mab.iu.Lienzo2D;
import sm.mab.iu.Lienzo2DImagen;


/**
 * Crea una ventana interna de imagen
 * @author Manuel Alonso Braojos
 */
public class VentanaInterna extends javax.swing.JInternalFrame {
    
    VentanaPrincipal ventPrincipal;
    Figura figura;
    
    /**
     * Constructor por defecto de la clase VentanaInterna
     */
    public VentanaInterna() {
        initComponents();
               
    }
    
    /**
     * Constructor por parámetros de la clase VentanaInterna
     * @param ventPr ventana principal 
     */
    public VentanaInterna(VentanaPrincipal ventPr) {
        initComponents();
        this.ventPrincipal = ventPr;
        this.lienzo2D1.setObjeto(1);//por defecto pintar en puntos
    }
    
    /**
     * Método para devolver el lienzo 
     * @return lienzo2D1 objeto lienzo
     */
    public Lienzo2DImagen getLienzo(){
        return this.lienzo2D1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D1 = new sm.mab.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Lienzo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo2D1.setBackground(new java.awt.Color(204, 204, 204));
        lienzo2D1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzo2D1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzo2D1Layout = new javax.swing.GroupLayout(lienzo2D1);
        lienzo2D1.setLayout(lienzo2D1Layout);
        lienzo2D1Layout.setHorizontalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        lienzo2D1Layout.setVerticalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        
        if(ventPrincipal!=null){
            ventPrincipal.setObjeto(lienzo2D1.getObjeto());
            ventPrincipal.setEditar(this.lienzo2D1.getEditar());
            ventPrincipal.setRelleno(this.lienzo2D1.getRelleno());
            
            
            BasicStroke grosActivo = (BasicStroke)lienzo2D1.getSk();    
            ventPrincipal.getGrosor().setValue((int) grosActivo.getLineWidth());
            //ventPrincipal.setTransparencia(this.lienzo2D1.getTransparencia());            
            ventPrincipal.setAlisado(this.lienzo2D1.getAlisado());   
           
        }
        ventPrincipal.repaint();
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2D1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2D1MouseMoved
        Point punto=MouseInfo.getPointerInfo().getLocation();
        int x=(int) punto.getX();
        int y=(int) punto.getY();
        Robot robot;
        try{
            robot= new Robot();
        //robot.delay(2000);
        Color color=robot.getPixelColor(x, y);
        ventPrincipal.setRGB(color);
        ventPrincipal.setPosX(x);
        ventPrincipal.setPosY(y);
        }catch(Exception e){}
    }//GEN-LAST:event_lienzo2D1MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.mab.iu.Lienzo2DImagen lienzo2D1;
    // End of variables declaration//GEN-END:variables
}
