/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;

import java.io.File;
import javax.sound.sampled.LineEvent;
import javax.sound.sampled.LineListener;
import sm.sound.SMClipPlayer;
import sm.sound.SMPlayer;
import static sun.audio.AudioPlayer.player;

/**
 * Crea una ventana interna de reproducción de audio
 * @author Manuel Alonso Braojos
 */
public class VentanaInternaReproductor extends javax.swing.JInternalFrame {

    
    SMClipPlayer player;
    
    /**
     * Constructor de la clase VentanaInternaReproductor
     * 
     * @param f archivo de tipo File 
     */
    public VentanaInternaReproductor(File f) {
        initComponents();
        player = new SMClipPlayer(f);
       
    }

    /**
     * Método que devuelver player
     * @return player objeto player
     */
    public SMClipPlayer getPlayer() {
        return player;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoAudio = new javax.swing.ButtonGroup();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoAudio;
    // End of variables declaration//GEN-END:variables
}
